MulberryWoods_EventScript_CorbinIntro::
# 1 "data/text/trainers_plychrme.pory"
	.string "Hey, you look pretty weak!\p"
	.string "I'll start my journey as a Pokémon \n"
	.string "Trainer by beating you!$"

MulberryWoods_EventScript_CorbinDefeated::
# 8 "data/text/trainers_plychrme.pory"
	.string "Aw, no fair!\n"
	.string "You're way stronger than me!$"

MulberryWoods_EventScript_CorbinPostBattle::
# 13 "data/text/trainers_plychrme.pory"
	.string "I guess I'm the one who started\n"
	.string "your journey instead...$"

MulberryWoods_EventScript_JesseIntro::
# 18 "data/text/trainers_plychrme.pory"
	.string "Another Pokémon for my collection!\p"
	.string "Go, go, go, my beautiful Bug team!$"

MulberryWoods_EventScript_JesseDefeated::
# 24 "data/text/trainers_plychrme.pory"
	.string "...Huh? Hey!\n"
	.string "You're just a trainer!$"

MulberryWoods_EventScript_JessePostBattle::
# 29 "data/text/trainers_plychrme.pory"
	.string "Um, sorry for hitting you with my net.\n"
	.string "I thought you were a Bug Pokémon...$"

MulberryWoods_EventScript_LiraIntro::
# 34 "data/text/trainers_plychrme.pory"
	.string "I'm doing an ecological survey on the\n"
	.string "Pokémon here for a school project.\l"
	.string "Check this out!$"

MulberryWoods_EventScript_LiraDefeated::
# 40 "data/text/trainers_plychrme.pory"
	.string "Oh! I lost already?$"

MulberryWoods_EventScript_LiraPostBattle::
# 44 "data/text/trainers_plychrme.pory"
	.string "I think there are more Pokémon \n"
	.string "somewhere deeper in these woods,\l"
	.string "but I don't know how to get there...$"

MulberryWoods_EventScript_TobyIntro::
# 50 "data/text/trainers_plychrme.pory"
	.string "Eek! H{PAUSE 60}-Hey!\n"
	.string "Who's there?!$"

MulberryWoods_EventScript_TobyDefeated::
# 55 "data/text/trainers_plychrme.pory"
	.string "This place gives me the creeps...$"

MulberryWoods_EventScript_TobyPostBattle::
# 59 "data/text/trainers_plychrme.pory"
	.string "Urgh... I really shouldn't have\n"
	.string "battled you.\p"
	.string "Now I'm too scared to walk home\n"
	.string "without my Pokémon...$"

MulberryWoods_EventScript_MichaelIntro::
# 66 "data/text/trainers_plychrme.pory"
	.string "You see this item that's next to me?\p"
	.string "If you want it, you're gonna have to\n"
	.string "defeat me first!$"

MulberryWoods_EventScript_MichaelDefeated::
# 73 "data/text/trainers_plychrme.pory"
	.string "Fine, I guess you can have it...$"

MulberryWoods_EventScript_MichaelPostBattle::
# 77 "data/text/trainers_plychrme.pory"
	.string "Huh? What's the item?\n"
	.string "Oh, I have no idea!$"
