MulberryWoods_EventScript_CorbinIntro::
# 1 "data/text/trainers_plychrme.pory"
	.string "Hey, you look pretty weak!\p"
	.string "I'll start my journey as a Pokémon \n"
	.string "Trainer by beating you!$"

MulberryWoods_EventScript_CorbinDefeated::
# 8 "data/text/trainers_plychrme.pory"
	.string "Aw, no fair!\n"
	.string "You're way stronger than me!$"

MulberryWoods_EventScript_CorbinPostBattle::
# 13 "data/text/trainers_plychrme.pory"
	.string "Looks like I'm the one who started\n"
	.string "your journey instead...$"

MulberryWoods_EventScript_JesseIntro::
# 18 "data/text/trainers_plychrme.pory"
	.string "Another one for my collection!\p"
	.string "Go, my Bug Pokémon!$"

MulberryWoods_EventScript_JesseDefeated::
# 24 "data/text/trainers_plychrme.pory"
	.string "...Huh? Hey!\n"
	.string "You're just a trainer!$"

MulberryWoods_EventScript_JessePostBattle::
# 29 "data/text/trainers_plychrme.pory"
	.string "Um, sorry for hitting you with my net.\n"
	.string "I thought you were a Bug Pokémon...$"

MulberryWoods_EventScript_LiraIntro::
# 34 "data/text/trainers_plychrme.pory"
	.string "This is a placeholder intro.$"

MulberryWoods_EventScript_LiraDefeated::
# 38 "data/text/trainers_plychrme.pory"
	.string "This is placeholder defeat text.$"

MulberryWoods_EventScript_LiraPostBattle::
# 42 "data/text/trainers_plychrme.pory"
	.string "This is placeholder post-battle text.$"
