#ifndef GUARD_GENERATED_ANIM_CODE_NewGeneral_H
#define GUARD_GENERATED_ANIM_CODE_NewGeneral_H

// Ensure INCBIN_U16 is available
#ifndef INCBIN_U16
#include "gba/defines.h"
#endif

/*
 * This file is auto-generated by Porytiles.
 * DO NOT EDIT THIS FILE MANUALLY (unless you know what you are doing).
 */

// ============================================
// Frame Data (INCBIN statements)
// ============================================

const u16 gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame0[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/p_flower/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame4[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/p_flower/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame3[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/p_flower/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame2[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/p_flower/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame1[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/p_flower/1.4bpp");

const u16 gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame0[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/r_flower/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame1[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/r_flower/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame2[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/r_flower/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame3[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/r_flower/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame4[] = INCBIN_U16("data/tilesets/primary/new_general/porytiles_bin/anim/r_flower/4.4bpp");

// ============================================
// Frame Pointer Arrays
// ============================================

const u16 *const gTilesetAnims_PorytilesManaged_NewGeneral_PFlower[] = {
    gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame0,
    gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame4,
    gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame3,
    gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame2,
    gTilesetAnims_PorytilesManaged_NewGeneral_PFlower_Frame1
};

const u16 *const gTilesetAnims_PorytilesManaged_NewGeneral_RFlower[] = {
    gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame0,
    gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame1,
    gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame2,
    gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame3,
    gTilesetAnims_PorytilesManaged_NewGeneral_RFlower_Frame4
};

// ============================================
// Queue Functions
// ============================================

static void QueueAnimTiles_PorytilesManaged_NewGeneral_PFlower(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_NewGeneral_PFlower);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_NewGeneral_PFlower[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(1)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_NewGeneral_RFlower(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_NewGeneral_RFlower);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_NewGeneral_RFlower[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(5)), 4 * TILE_SIZE_4BPP);
}

// ============================================
// Driver Function
// ============================================

static void TilesetAnim_PorytilesManaged_NewGeneral(u16 timer)
{
    if (timer % 16 == 0)
    {
        QueueAnimTiles_PorytilesManaged_NewGeneral_RFlower(timer / 16);
    }
    if (timer % 16 == 1)
    {
        QueueAnimTiles_PorytilesManaged_NewGeneral_PFlower(timer / 16);
    }
}

// ============================================
// Init Function
// ============================================

void InitTilesetAnim_PorytilesManaged_NewGeneral(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_PorytilesManaged_NewGeneral;
}

#endif // GUARD_GENERATED_ANIM_CODE_NewGeneral_H
